sudo: required
dist: trusty

language: cpp
compiler:
  - gcc
  - clang

env:
  global:
    # The next declaration is the encrypted COVERITY_SCAN_TOKEN, created
    #   via the "travis encrypt" command using the project repo's public key
    - secure: "oYIV1EmOvP2ruIxyCTPuGuqUsUzTxxu3P+IdlQZgV6aXaBxtFCuoQaLVMOlnx8xSI2V4mb5I/wK5fAtgUAomzDHQmaBNSbJc3xBTy2xgckup60ehKtFqf+ifm+AYcLQQgLtMUDmLNNcJIKUGPZ8GYwjNfWKt3VGuLHV+UFiRuQI="
    - coverity_scan_run_condition='\( "$CC" = gcc \) -a \( $USECMAKE -eq 0 \)'
    - coverity_scan_script_test_mode=false
  matrix:
    # Let's test both our autoconf and CMake build systems
    - USECMAKE=0
    - USECMAKE=1

# Only test gcc with autotools, not CMake.
# We now have three builds: autoconf+gcc, autoconf+clang, CMake+clang
# Note: In the other xoreos repositories, we use gcc for the CMake test.
#       However, for the main xoreos repository, it fails to link in
#       the Travis CI Trusty worker, for some reason. It does work on
#       other systems, so it might be an intermittent gcc bug?
matrix:
  exclude:
    - compiler: gcc
      env: USECMAKE=1

script:
  # Configure, autotools
  - if [ \( "$COVERITY_SCAN_BRANCH" != 1 \) -a \( $USECMAKE -eq 0 \) ]; then ./autogen.sh; fi
  - if [ \( "$COVERITY_SCAN_BRANCH" != 1 \) -a \( $USECMAKE -eq 0 \) ]; then ./configure || cat config.log; fi
  # Configure, CMake
  - if [ \( "$COVERITY_SCAN_BRANCH" != 1 \) -a \( $USECMAKE -eq 1 \) ]; then cmake .; fi
  # Compile
  - if [ "$COVERITY_SCAN_BRANCH" != 1 ]; then make -j4; fi
  # Unit tests, autotools
  - if [ \( "$COVERITY_SCAN_BRANCH" != 1 \) -a \( $USECMAKE -eq 0 \) ]; then echo "" > test-suite.log; make -j4 check || cat test-suite.log; fi
  # Unit tests, CMake
  - if [ \( "$COVERITY_SCAN_BRANCH" != 1 \) -a \( $USECMAKE -eq 1 \) ]; then make -j4 check; fi

addons:
  apt:
    packages:
      - libboost-all-dev
      - libsdl2-dev
      - libopenal-dev
      - libfreetype6-dev
      - libmad0-dev
      - libfaad-dev
      - libvorbis-dev
      - libxvidcore-dev
      - libgl1-mesa-dev
      - zlib1g-dev
      - liblzma-dev
      - libxml2-dev
  coverity_scan:
    build_script_url: https://raw.githubusercontent.com/$TRAVIS_REPO_SLUG/$TRAVIS_BRANCH/.travis_coverity.sh
    project:
      name: $TRAVIS_REPO_SLUG
    notification_email: drmccoy@drmccoy.de
    build_command_prepend: "./autogen.sh && ./configure"
    build_command: "make -j4 check"
    branch_pattern: coverity_scan

notifications:
  email:
    recipients:
      - ndbrandes@gmail.com
    on_success: change
    on_failure: always
  irc:
    channels:
      - secure: "Q7G5gmVRO67LIAhic4NoeiPRtygiOqjEfPZMIHqgTcpd1OkD8u/Sv9zhfYORfCIqKX1TruL6to6O/4q0HdjQ4NL4GfiNB0iYc+JCinmg80ekPLjjxBIvHmrsvz8onTAmxyYFacXM0YNurCMVvuD0F/yUaiTWwVcRY7PId8T8KPk="
    on_success: change
    on_failure: always
    use_notice: true

deploy:
  provider: releases
  api_key:
    secure: mX4FE1jDRGoa65K0E5DyhZHTZzQ750WC6shghMWehZX7VAd3r/+LRSLE7P5xVVh+K7FvpR1FG+C5UcGzNsy8GBCk0Am6IoKfjs1TPsyA16VJ93nTL6fdzzyvvpWPlmJuuOEEDt+iRFvHtXE/yqNy+q9ekjUvH49H1RRpuFQdvjFMmEv5sdaWzivcQc4fv6p1rTLgJeY7zJOY8rGjB6n1ev/A6lLHZQSnl7OnonLDpuawsMMWl34cJu0MBVrRwIAIgSO6eylCHWvPDa9vgUUM4ipzT2j+QB2RedwPDrRWC5pZro81JccoZvQh+9MMltU0LZUlrQAkDYE65ss10+Lo2PPoeWBf7L3b2gWKx42rf0MDUBUkWj1+odBMc3eNHdXGEs/CKUhn3Zwb9vgemOCdgoYXWaKkLhnbnNqe1spcZ2bJe0oiZ72P9TeFzcnBP/T28zpr/3R6lXs0L95e8A026yTWhdonmNOt+d1ciueSldnkuQ3iZqyIQOC/guIOUGiX8KiF97CcWP9yYwhC46BFuymLHrV1yO3Zm+EQUdvyRQ6EaQumNf5c0Q2/I/q7Brn6IgDHC3IbO6UaUvGn3VJvzqt+VCdtG8zD60jQZWVtEm1MkPZXhMYml5hykEWndV/VpckZ/y2Yab4O7uTc15eOARAXV0vqrpzA3FD5XSb6EPc=
  file: 'AUTHORS'
  on:
    branch: master
